baseurl = "https://UW-POLS501.github.io/2018/"
languageCode = "en-US"
title = "POLS 501: Advanced Political Research Design and Analysis"
theme = "pols-501"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# Set to docs for GitHub pages
publishDir = "docs"


[permalinks]
    post = "/:year/:month/:day/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "Schedule"
    url = "/schedule/"

[[menu.main]]
    name = "Assignments"
    url = "/assignments/"

[[menu.main]]
    name = "Projects"
    url = "/projects/"

[[menu.main]]
    name = "Pages"
    url = "/pages/"


[params]
    # if true, includes a big button
    inprogress = false
    description = "The website Website for University of Washington: POLS 501 \"Advanced Political Research Design and Analysis\" (Winter 2018)."
    sourceUrl = "https://github.com/UW-POLS501/2018/"

    [params.license]
      name = "Creative Commons Attribution 4.0 International License"
      URL = "http://creativecommons.org/licenses/by/4.0/"

    [params.NavbarBrand]
    name = "POLS 501"
    URL = "/"

    [params.instructor]
      name = "Jeffrey B. Arnold"
      title = "Assistant Professor, Political Science; Core Faculty, CSSS"
      email = "jrnold@uw.edu"
      url = "https://jrnold.com"
      [params.instructor.officeHours]
        time = "Monday, 2&ndash;4 pm"
        room = "Smith 221B"

    [params.ta]
      name = "Calvin Garner"
      title = "Graduate Student, Political Science"
      email = "chgarner@uw.edu"
      url = "https://www.polisci.washington.edu/people/calvin-garner"
      [params.ta.officeHours]
        time = "Thursday, 2&ndash;4 pm"
        room = "Gowen 30"

    [params.course]
      title = "Advanced Political Research Design and Analysis"
      number = "POLS/CS&SS 501"
      institution = "University of Washington"
      term = "Winter"
      year = "2018"

    mailing_lists = [
      "pols501a_wi18@uw.edu",
      "csss501a_wi18@uw.edu"
    ]

    [params.class]
      startTime = "2018-01-09T16:30:00-08:00"
      endTime = "2018-01-09T19:20:00-08:00"
      [params.class.room]
        building = "Savery"
        number = "140"
        url = "https://www.washington.edu/maps/#!/sav"


    [params.lab]
      startTime = "2018-01-05T13:30:00-08:00"
      endTime = "2018-01-05T15:20:00-08:00"
      [params.lab.room]
        building = "Savery"
        number = "121"
        url = "https://www.washington.edu/maps/#!/sav"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    # Bootstrap options
    useBootstrap = true

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
